### ISSUE TITLE
Link to Quixote

### ISSUE THREAD

**Issue by rojalator** [twill-tools/twill#20]
On the 'Developing Twill', 'Package tests' page the link to Quixote no longer works: I suggest correcting it (to, say, https://github.com/nascheme/quixote)

**Comment by Cito** [comment]
Thank you, it's fixed now. Quixote should be probably replaced sooner or later.

**Comment by rojalator** [comment]
Ah. I came across this issue while starting an update to Session3 for Quixote! (The tests are written in nose / twill)

**Comment by Cito** [comment]
Maybe that was mistakable. I meant, I want to replace Quixote with something else like bottle for testing twill. Don't know whether Quixote is still maintained or how widely used it is.

**Comment by rojalator** [comment]
It's still maintained - as for use it's not wide, I think (although douban uses it from what I remember, as does Linux Weekly News). Anyhow, thanks for the update.
