### ISSUE TITLE
 twill.shell.main() throws UnboundLocalError: cannot access 'output' 

### ISSUE THREAD

**Issue by Slipery** [twill-tools/twill#21]
Sorry to be a pain here but I am not sure where else I should go. I am relatively new to Python  also and I am sure the problem is mine but could someone help me out here please.

I am using Windows 11 Python 3.12 and latest twill.
I am trying to get twill running for the first time and followed this https://twill-tools.github.io/twill/install.html instruction 
But when following the troubleshooting section  in  the python shell I enter the following 

import twill.shell
twill.shell.main()

and get the following 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mal_r\AppData\Local\Programs\Python\Python312\Lib\site-packages\twill\shell.py", line 458, in main
    set_output(output)
               ^^^^^^
UnboundLocalError: cannot access local variable 'output' where it is not associated with a value
>>>

Thanks In advance

**Comment by Cito** [comment]
Thanks a lot for reporting this, @Slipery.

The last version had in fact an error in the interactive shell. It is fixed now in version 3.2.2.
