### ISSUE TITLE
New timeout() command cannot be found

### ISSUE THREAD

**Issue by jonathortense** [twill-tools/twill#22]
Sorry if I'm doing something wrong here, but I'm trying to use the new `timeout()` command but it's not working as I'm expecting.

This works:

```
import twill
twill.commands.timeout(60)
```

but this doesn't:

```
from twill.commands import *
timeout(60)
```

It returns:

```
NameError: name 'timeout' is not defined
```

I'm already using `from twill.commands import *` for other commands like `go()`, `showforms()` and it works as expected, but for `timeout()` it doesn't.

---
Python v3.11.6
twill==3.2.2

**Comment by Cito** [comment]
Thank you for reporting this. It's fixed now in version 3.2.3.
