### ISSUE TITLE
'charmap' codec can't encode character

### ISSUE THREAD

**Issue by rickproza** [twill-tools/twill#8]
I got this error when I was trying to save an HTML. Generally the reason is that twill is storing the html in non-utf8 file and there was a character with code  '\u2008'. Proposed fix: change line 253 in file commands.py to "f = open(filename, 'w', encoding="utf-8")".

**Comment by Cito** [comment]
Thank you for the report and the PR, @rickproza. I modified this a bit more in 3cd700ad778362615b4896fcb1a875469bec94c9 by first trying to save with the browser encoding, and only using utf-8 if that fails.
